// courtsData.js
export const courts = [
    {
        __id: "6569c65cfc13ae761a4cd2de",
        address: "zayed",
        email: "13@dell.com",
        courtname: "Court B",
        photo: "/users_images/users (13).png",
        phone: "103-375-8934",
    },
    {
        __id: "6lkfvnlkrsd4cd2de",
        address: "6-october",
        email: "12@dell.com",
        courtname: "Court C",
        photo: "/users_images/users (12).png",
        phone: "103-375-8934",
    },
    {
        __id: "6569cfc13ae761a4cd2de",
        address: "zayed",
        email: "4@dell.com",
        courtname: "Court D",
        photo: "/users_images/users (4).png",
        phone: "103-375-8934",
    },
    {
        __id: "65761a4cd2de",
        address: "shobra",
        email: "3@dell.com",
        courtname: "Court E",
        photo: "/users_images/users (3).png",
        phone: "103-375-8934",
    },
    {
        __id: "656d2de",
        address: "helwan",
        email: "2@dell.com",
        courtname: "Court F",
        photo: "/users_images/users (2).png",
        phone: "103-375-8934",
    },
    {
        __id: "6569c65cfcjdjdjda4cd2de",
        address: "6-october",
        email: "1@dell.com",
        courtname: "Court G",
        photo: "/users_images/users (9).png",
        phone: "103-375-8934",
    },
    {
        __id: "6569",
        address: "giza",
        email: "6@dell.com",
        courtname: "Court H",
        photo: "/users_images/users (6).png",
        phone: "103-375-8934",
    },
    {
        __id: "e761a4cd2de",
        address: "cairo",
        email: "7@dell.com",
        courtname: "Court I",
        photo: "/users_images/users (7).png",
        phone: "103-375-8934",
    },
    {
        __id: "abcd1234efgh5678ijkl",
        address: "maadi",
        email: "8@dell.com",
        courtname: "Court J",
        photo: "/users_images/users (8).png",
        phone: "103-375-8934",
    },
    {
        __id: "mnop5678qrst9101uvwx",
        address: "zamalek",
        email: "9@dell.com",
        courtname: "Court K",
        photo: "/users_images/users (10).png",
        phone: "103-375-8934",
    },
    {
        __id: "yz1234abcd5678efgh90",
        address: "new cairo",
        email: "10@dell.com",
        courtname: "Court L",
        photo: "/users_images/users (11).png",
        phone: "103-375-8934",
    },
    {
        __id: "ijkl5678mnop9101uvwx",
        address: "helwan",
        email: "11@dell.com",
        courtname: "Court M",
        photo: "/users_images/users (12).png",
        phone: "103-375-8934",
    }
];
export default courts;
